language: node_js
node_js:
    - node 
script: cd api && yarn install && yarn test
deploy:
    on:
        branch: 'master'
    skip_cleanup: true
    provider: script
    script: npm install -g serverless && cd api && yarn build && serverless deploy
    