language: node_js
node_js:
- node
script: cd api && yarn install && yarn test
deploy:
  skip_cleanup: true
  provider: script
  script: pwd && npm install -g serverless && yarn build && serverless deploy
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
