backend:
  name: github
  repo: aliemteam/aliemcards_cards
  branch: netlifycms
publish_mode: editorial_workflow
media_folder: "cards/media"
public_folder: "media"
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "cards" # Used in routes, e.g., /admin/collections/blog
    label: "Cards" # Used in the UI
    folder: "/cards" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Created", name: "created", widget: "string"}
      - {label: "Updated", name: "updated", widget: "string", required: false}
      - {label: "Categories", name: "categories", widget: "list"}
      - label: "Card Authors"
        name: "authors"
        widget: "list"
        field:
          - { label: "Name", name: "name", widget: "string" }
      - {label: "Body", name: "body", widget: "markdown"}
      
