service: aliemcards_search

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  search:
    handler: handler.search
    events:
      - http:
          path: /{query}
          method: get
