service: aliemcards-search

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1024

package:
  exclude:
    - tests/**
  include:
    - ../../node_modules/fuse.js/**
    - ../../dist/cards.json

functions:
  search:
    handler: handler.search
    events:
      - http:
          path: search/{query}
          method: get
          cors: true
