service: aliemcards-search

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 1024

package:
  exclude:
    - node_modules/**
    - build/**
    - dist/**
  include:
    - node_modules/fuse.js/**
    - dist/cards.json
    - dist/cardsummaries.json

functions:
  search:
    handler: lambda/handler.search
    events:
      - http:
          path: search/{query}
          method: get
